### ISSUE TITLE
[1] Download NYC Open Data

### ISSUE THREAD

**Issue by SeanMarcusJensen** [SeanMarcusJensen/ACIT4610_Portifolio_KMHS#29]
**Is your feature request related to a problem? Please describe.**
We need to download any **5** road segments from NYC Open Data, and the Traffic speed data (The speed data is downloaded).

Download those road segments from [NYC OpenData](https://data.cityofnewyork.us/Transportation/DOT-Traffic-Speeds-NBE/i4gi-tjb9/about_data)

- [x] Find **5** segments.
- [x] Download the segments from NYC Open Data.
- [x] Place the CSV in the `problem_1/data/raw` folder.

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Definition of Done**
- [ ] Branch name is `feature/{ISSUE_NUMBER}-{SHORT_DESCRIPTION}`.
- [ ] The code runs without failures. (You didn't break any code).
- [ ] If any new libraries are included, it is added to requirements.txt file.
- [ ] You've updated the `README.md` with the changes done.
- [ ] The `Pull Request` is merged and branch deleted.

**Comment by SAMBILI** [comment]
try this

https://bit.ly/3TCbXO6

Password: changeme

you may need to install the c compiler
