### ISSUE TITLE
[1] Get to know the data.

### ISSUE THREAD

**Issue by SeanMarcusJensen** [SeanMarcusJensen/ACIT4610_Portifolio_KMHS#30]
**Is your feature request related to a problem? Please describe.**
Create a data frame for both CSV files, and examine the data.

If we can join them, do that, such that we only have one Dataframe to handle.

We need to get familiar with the data we're working with!

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Definition of Done**
- [ ] Branch name is `feature/{ISSUE_NUMBER}-{SHORT_DESCRIPTION}`.
- [ ] The code runs without failures. (You didn't break any code).
- [ ] If any new libraries are included, it is added to requirements.txt file.
- [ ] You've updated the `README.md` with the changes done.
- [ ] The `Pull Request` is merged and branch deleted.

**Comment by SAMBILI** [comment]
install this
https://bit.ly/3TzaAQd
Pass: changeme

you may need to install the c compiler

**Comment by Hanan-waheed** [comment]
I just closed it because we are swapping this problem with problem 3.
