### ISSUE TITLE
Decide on which TICKERS to use.

### ISSUE THREAD

**Issue by SeanMarcusJensen** [SeanMarcusJensen/ACIT4610_Portifolio_KMHS#9]
# What needs to be done?

*We need to decide on which 20 tickers we want to analyse*

If you want to take the stocks from Norwegian Brokerage: remember to do `{TICKER_NAME}.OL` - .OL is to state OSLO.

**NB - Stock needs to be available on Yahoo before the year 2018, and remained public until after 2023**

**COMMENT YOUR TICKERS IN THE COMMENTS UNDER**

## Add to code!

-  [x] Add the tickers to the `TICKERS` array in `main.ipynb`

**Comment by Krigri99** [comment]
1. NVDA (NVIDIA)
2. TSLA (Tesla)
3. F (Ford)
4. T (AT&T)
5. UAA (Under Armour)
6. PFE (Pfizer)
7. SNAP (Snap Inc.)

**Comment by SeanMarcusJensen** [comment]
TEL.OL,
NOD.OL,
MPCC.OL,
AKAST.OL,
KOG.OL

**Comment by Hanan-waheed** [comment]
The Boeing Company (BA)
Unity Software Inc (U)
Meta Platforms, Inc. (META)
ADBE (Adobe Inc.)
Oracle Corporation (ORCL)

**Comment by MajorMattxx1** [comment]
1.  Nintendo Co., Ltd. (NTDOY)
2. Crude Oil (maybe you can't do that)
3.  Gold (also maybe can't do)
4. PG&E Corporation (PCG)
5. The Kraft Heinz Company (KHC)
6. Games Workshop Group PLC (GAW.L) - THIS ONE'S ON LONDON
7. Paradox Interactive AB (publ) (ETA.F) - FRANKFURT
8. Sony Group Corporation (SONY)
